version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2017
nuget:
  disable_publish_on_pr: true
build_script:
- cmd: .\psake.cmd ci
test: off
artifacts:
- path: build\results\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  server: https://www.myget.org/F/simpleidserver/api/v3/index.json
  api_key:
    secure: iW1+rHmTmrADJlwbWH3QCFAKRZHJ14XxCWfDAN0b01Oov5G/N4eEjFG+RrwvppwE
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  name: production
  api_key:
    secure: sCWC9q0qyTq//EuhS9kjMCqRDWaH5iF//mQrkraUiYoEjbVIWc/YQ3z3cB+wsbce
  on:
    branch: master
    appveyor_repo_tag: true
