version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2022
install:
- ps: "Import-Certificate -FilePath \"C:\\projects\\simpleidserver\\certificates\\simpleIdServerClient.crt\" -CertStoreLocation cert:\\LocalMachine\\Root\nImport-Certificate -FilePath \"C:\\projects\\simpleidserver\\certificates\\simpleIdServerClient.crt\" -CertStoreLocation cert:\\CurrentUser\\Root \n Install-Module VSSetup -Scope CurrentUser"
nuget:
  disable_publish_on_pr: true
build_script:
- cmd: .\psake.cmd ci
test: off
artifacts:
- path: build\results\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  server: https://www.myget.org/F/advance-ict/api/v2/package
  api_key:
    secure: zs1JVjFHRdvB36fGq2rN8MR7QeJnCVkt7VTG4ZHT5OYDNpuh2AlGHqK+rseevn8l
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master
- provider: NuGet
  name: production
  artifact: /.*\.nupkg/
  api_key:
    secure: YxYVFFNdgFPI6atwwV80ZBy/waXfipraBVGfE+huQEj4ItqfNJDHnX8q8R4Fybse
  on:
    branch: master
    appveyor_repo_tag: true