version: "3.9"
services:
  rabbitmq:
    image: "rabbitmq:3.9.5-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    expose:
     - 15672
     - 5672
  db:
    build:
      context: .
      dockerfile: ./DbDockerFile
    image: simpleidserver/db:2.0.0
    volumes:
     - mssqldata:/var/opt/mssql
  openid:
    build:
      context: .
      dockerfile: ./OpenIdDockerFile
    image: simpleidserver/openid:2.0.0
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
      ASPNETCORE_URLS : "https://*:60000"
    ports:
      - "60000:60000"
    depends_on:
      - db
      - rabbitmq
  scim:
    build:
      context: .
      dockerfile: ./ScimDockerFile
    image: simpleidserver/scim:2.0.0
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    ports:
      - "60002:60002"
    depends_on:
      - db
      - rabbitmq
      - samlidp
  bpmn:
    build:
      context: .
      dockerfile: ./BpmnDockerFile
    image: simpleidserver/bpmn:2.0.0
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
      ASPNETCORE_URLS : "http://*:60007"
    ports:
      - "60007:60007"
    depends_on:
      - openid
      - humantask
  humantask:
    build:
      context: .
      dockerfile: ./HumanTaskDockerFile
    image: simpleidserver/humantask:2.0.0
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
      ASPNETCORE_URLS : "http://*:60006"
    ports:
      - "60006:60006"
    depends_on:
      - openid
  samlidp:
    build:
      context: .
      dockerfile: ./SamlIdpDockerFile
    image: simpleidserver/samlidp:2.0.0
    environment:
      ASPNETCORE_URLS : "http://*:7000"
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
      ASPNETCORE_URLS : "http://*:7000"
    ports:
      - "7000:7000"
    depends_on:
      - openid
  gateway:
    build:
      context: .
      dockerfile: ./GatewayDockerFile
    image: simpleidserver/gateway:2.0.0
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
      ASPNETCORE_URLS : "http://*:5001"
    ports:
      - "5001:5001"
    depends_on:
      - openid
      - scim
      - bpmn
      - humantask
      - samlidp
  website:
    build:
      context: .
      dockerfile: ./WebsiteDockerFile
    image: simpleidserver/website:2.0.0
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
      ASPNETCORE_URLS : "http://*:4200"
    ports:
      - "4200:4200"
  provisioning:
    build:
      context: .
      dockerfile: ./ProvisioningDockerFile
    image: simpleidserver/provisioning:2.0.0
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    depends_on:
      - db
      - rabbitmq
      - openid
      - bpmn
      - scim
volumes:
  mssqldata: