version: "3.9"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    volumes:
     - mssqldata:/var/opt/mssql
  idserver:
    build:
      context: .
      dockerfile: ./OpenIdDockerFile
    image: simpleidserver/idserver:${TAG}
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
      ASPNETCORE_URLS : "https://*:60000"
      ConnectionString: ""
    ports:
      - "60000:60000"
    depends_on:
      - db
  website:
    build:
      context: .
      dockerfile: ./WebsiteDockerFile
    image: simpleidserver/website:${TAG}
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
      ASPNETCORE_URLS : "http://*:4200"
      ConnectionString: ""
    ports:
      - "4200:4200"
    depends_on:
      - db
volumes:
  mssqldata: